### ISSUE TITLE
Crash while initializing

### ISSUE THREAD

**Issue by bursacmilan** [bursacmilan/divoom-homey#6]
Hello,
If I switch off Pixoo, be it from the Divoom app or Homey, the device becomes unreachable in Homey : "Fetch failed".
I have set a fixed IP and checked that it is still the same but the device gets unreachable every time I keep it off for a few hours.
I need to delete it and add it again in Homey to have it work

    stdout:
    2024-10-30T00:42:14.025Z [log] [MyApp] MyApp has been initialized
2024-10-30T00:42:15.697Z [log] [ManagerDrivers] [Driver:divoom-pixoo-64] [Device:b19ba260-3731-44e1-a23d-53772b4ad60e] ipAddress: 192.168.1.23, deviceId: 300172839, macAddress: 08a6f796a6c0

    stderr:
    2024-10-30T00:42:19.209Z [err] [ManagerDrivers] [Driver:divoom-pixoo-64] [Device:b19ba260-3731-44e1-a23d-53772b4ad60e] Device.onInit Error: TypeError: fetch failed
    at node:internal/deps/undici/undici:12618:11
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async DivoomApi._sendCommand (/app/shared/divoom/divoom-api.js:43:30)
    at async DivoomApi.sendCommandImmediatelyAndGet (/app/shared/divoom/divoom-api.js:18:28)
    at async Pixoo64Device.onInit (/app/drivers/divoom-pixoo-64/device.js:26:30)
    at async Pixoo64Device._onInit (/node_modules/@athombv/homey-apps-sdk-v3/lib/Device.js:148:7) {
  cause: Error: connect EHOSTUNREACH XX
      at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1555:16) {
    errno: -113,
    code: 'EHOSTUNREACH',
    syscall: 'connect',
    address: 'XX',
    port: 80

**Comment by bursacmilan** [comment]
Fixed in Version 1.1.1
